development:
  adapter: postgresql
  encoding: unicode
  database: contact_manager_dev
  username: gschool_user
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: contact_manager_test
  username: gschool_user
  password: password
  host: localhost
  port: 5432  

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: contact_manager
#   username: gschool_user
#   password: password
#   host: localhost
#   port: 5432